politicaEscalonamento: RoundRobin

programas:
  - fonte: prog1.txt
    instanteCarga: 10
    quantum: 2
  - fonte: prog1.txt
    instanteCarga: 11
    quantum: 3
  - fonte: prog2.txt
    instanteCarga: 20
    quantum: 5